name: Reusable Build & Deploy Workflow

on:
  workflow_call:
    inputs:
      resource_group:
        required: true
        type: string
      aks_name:
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        required: true

jobs:
  build_and_push:
    name: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout caller repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar

  deploy_to_kubernetes:
    name: deploy-to-production
    runs-on: ubuntu-latest
    needs: build_and_push
    environment:
      name: production
    steps:
      - name: Checkout caller repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: latest

      - name: Get AKS credentials
        run: |
          az aks get-credentials \
            --resource-group ${{ inputs.resource_group }} \
            --name ${{ inputs.aks_name }} \
            --overwrite-existing \
            --admin

      - name: Deploy to AKS
        run: |
          echo "Deploying application to production..."
          kubectl apply -f ds.yml --validate=false
          kubectl rollout status deployment/bankapp-deployment --timeout=120s || true
